create table if not exists schema_migration (
  migration_id varchar(255) primary key,
  checksum char(64) not null,
  applied_at timestamptz not null default now()
);

create table if not exists advertiser (
  advertiser_id integer generated by default as identity primary key,
  advertiser_name varchar(255) not null,
  external_id varchar(100),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by varchar(100),
  updated_at timestamptz,
  updated_by varchar(100)
);

create unique index if not exists ux_advertiser_name
  on advertiser (advertiser_name);

create unique index if not exists ux_advertiser_external_id
  on advertiser (external_id)
  where external_id is not null;

create table if not exists offer (
  offer_id integer generated by default as identity primary key,
  advertiser_id integer not null references advertiser(advertiser_id),
  offer_name varchar(255) not null,
  external_id varchar(100),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by varchar(100),
  updated_at timestamptz,
  updated_by varchar(100)
);

create unique index if not exists ux_offer_advertiser_name
  on offer (advertiser_id, offer_name);

create unique index if not exists ux_offer_advertiser_external_id
  on offer (advertiser_id, external_id)
  where external_id is not null;

create table if not exists publisher (
  publisher_id integer generated by default as identity primary key,
  publisher_name varchar(255) not null,
  external_id varchar(100),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by varchar(100),
  updated_at timestamptz,
  updated_by varchar(100),
  contact_name varchar(255),
  contact_email varchar(255),
  website_url varchar(500),
  registration_notes text,
  registration_status varchar(50) not null default 'approved',
  password_hash varchar(500),
  password_set_at timestamptz,
  last_login_at timestamptz
);

create unique index if not exists ux_publisher_name
  on publisher (publisher_name);

create unique index if not exists ux_publisher_external_id
  on publisher (external_id)
  where external_id is not null;

create index if not exists ix_publisher_contact_email
  on publisher (contact_email);

create table if not exists publisher_offer (
  publisher_offer_id integer generated by default as identity primary key,
  publisher_id integer not null references publisher(publisher_id),
  offer_id integer not null references offer(offer_id),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by varchar(100),
  updated_at timestamptz,
  updated_by varchar(100)
);

create unique index if not exists ux_publisher_offer_publisher_offer
  on publisher_offer (publisher_id, offer_id);

create table if not exists account (
  account_id integer generated by default as identity primary key,
  email_address varchar(320) not null,
  password_hash varchar(500) not null,
  email_verified_at timestamptz,
  status varchar(50) not null default 'active',
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);

create unique index if not exists ux_account_email_address
  on account (email_address);

create table if not exists auth_session (
  auth_session_id integer generated by default as identity primary key,
  account_id integer not null references account(account_id) on delete cascade,
  session_token_hash varchar(128) not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz
);

create unique index if not exists ux_auth_session_session_token_hash
  on auth_session (session_token_hash);

create index if not exists ix_auth_session_account_id
  on auth_session (account_id);

create table if not exists auth_challenge (
  auth_challenge_id integer generated by default as identity primary key,
  account_id integer not null references account(account_id) on delete cascade,
  challenge_type varchar(50) not null,
  code_hash varchar(128) not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz
);

create index if not exists ix_auth_challenge_code_hash
  on auth_challenge (code_hash);

create index if not exists ix_auth_challenge_account_type
  on auth_challenge (account_id, challenge_type, used_at, expires_at);

create table if not exists widget_queue_demo (
  widget_id integer generated by default as identity primary key,
  widget_name varchar(200) not null,
  status varchar(50) not null default 'queued',
  created_at timestamptz not null default now(),
  queued_at timestamptz,
  processing_started_at timestamptz,
  processed_at timestamptz,
  process_count integer not null default 0,
  last_message_id varchar(100),
  last_error text
);

create index if not exists ix_widget_queue_demo_status_created_at
  on widget_queue_demo (status, created_at desc);

create table if not exists widget_consumer_demo (
  widget_id integer generated by default as identity primary key,
  widget_name varchar(200) not null,
  status varchar(50) not null default 'queued',
  created_at timestamptz not null default now(),
  queued_at timestamptz,
  processing_started_at timestamptz,
  processed_at timestamptz,
  processed_by varchar(100),
  processing_seconds integer,
  last_message_id varchar(100),
  last_error text
);

create index if not exists ix_widget_consumer_demo_status_created_at
  on widget_consumer_demo (status, created_at desc);
