services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cm-platform-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "#Pop,6300"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: cm-platform-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: cm_platform
      RABBITMQ_DEFAULT_PASS: cm_platform_dev
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  mssql_data:
    external: true
    name: docker_mssql_data
  rabbitmq_data:
    name: cm_platform_rabbitmq_data
